services:
  - type: web
    name: verba
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: "verba-index"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://verba-6s5h.onrender.com"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_STORAGE_URL
        sync: false
      - key: SUPABASE_STORAGE_KEY
        sync: false
      - key: SUPABASE_STORAGE_SECRET
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        value: "verba-uploads"
